# Multi-stage Dockerfile for Next.js App with Bun
FROM oven/bun:1-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# Build the app
FROM base AS builder
WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# Build arguments for agent configuration
ARG NEXT_PUBLIC_AGENT_ID
ARG NEXT_PUBLIC_AGENT_NAME
ARG NEXT_PUBLIC_AGENT_DISPLAY_NAME
ARG NEXT_PUBLIC_AGENT_DESCRIPTION
ARG NEXT_PUBLIC_AGENT_SHORT_DESCRIPTION
ARG NEXT_PUBLIC_AGENT_DOMAIN
ARG NEXT_PUBLIC_AGENT_THEME
ARG NEXT_PUBLIC_PRIMARY_COLOR
ARG NEXT_PUBLIC_SECONDARY_COLOR
ARG NEXT_PUBLIC_ACCENT_COLOR
ARG NEXT_PUBLIC_AGENT_LOGO
ARG NEXT_PUBLIC_AGENT_BANNER_LOGO
ARG NEXT_PUBLIC_AGENT_LOGIN_IMAGE
ARG NEXT_PUBLIC_AGENT_FAVICON
ARG NEXT_PUBLIC_AGENT_OG_IMAGE
ARG NEXT_PUBLIC_WELCOME_MESSAGE
ARG NEXT_PUBLIC_AGENT_TAGLINE
ARG NEXT_PUBLIC_EXAMPLE_PROMPTS
ARG NEXT_PUBLIC_AGENT_KEYWORDS
ARG NEXT_PUBLIC_ABOUT_CONTENT
ARG NEXT_PUBLIC_AGENT_X_USERNAME
ARG NEXT_PUBLIC_AGENT_DISCORD_SERVER
ARG NEXT_PUBLIC_AGENT_WEBSITE_URL
ARG NEXT_PUBLIC_AGENT_GITHUB_URL
ARG NEXT_PUBLIC_ENABLE_DEEP_RESEARCH
ARG NEXT_PUBLIC_ENABLE_FILE_UPLOAD
ARG NEXT_PUBLIC_ENABLE_TEXT_TO_SPEECH
ARG NEXT_PUBLIC_ENABLE_VOICE_INPUT
ARG NEXT_PUBLIC_ENABLE_VOTING
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_WORLD_ID

# Set environment variables for build
ENV NEXT_PUBLIC_AGENT_ID=$NEXT_PUBLIC_AGENT_ID
ENV NEXT_PUBLIC_AGENT_NAME=$NEXT_PUBLIC_AGENT_NAME
ENV NEXT_PUBLIC_AGENT_DISPLAY_NAME=$NEXT_PUBLIC_AGENT_DISPLAY_NAME
ENV NEXT_PUBLIC_AGENT_DESCRIPTION=$NEXT_PUBLIC_AGENT_DESCRIPTION
ENV NEXT_PUBLIC_AGENT_SHORT_DESCRIPTION=$NEXT_PUBLIC_AGENT_SHORT_DESCRIPTION
ENV NEXT_PUBLIC_AGENT_DOMAIN=$NEXT_PUBLIC_AGENT_DOMAIN
ENV NEXT_PUBLIC_AGENT_THEME=$NEXT_PUBLIC_AGENT_THEME
ENV NEXT_PUBLIC_PRIMARY_COLOR=$NEXT_PUBLIC_PRIMARY_COLOR
ENV NEXT_PUBLIC_SECONDARY_COLOR=$NEXT_PUBLIC_SECONDARY_COLOR
ENV NEXT_PUBLIC_ACCENT_COLOR=$NEXT_PUBLIC_ACCENT_COLOR
ENV NEXT_PUBLIC_AGENT_LOGO=$NEXT_PUBLIC_AGENT_LOGO
ENV NEXT_PUBLIC_AGENT_BANNER_LOGO=$NEXT_PUBLIC_AGENT_BANNER_LOGO
ENV NEXT_PUBLIC_AGENT_LOGIN_IMAGE=$NEXT_PUBLIC_AGENT_LOGIN_IMAGE
ENV NEXT_PUBLIC_AGENT_FAVICON=$NEXT_PUBLIC_AGENT_FAVICON
ENV NEXT_PUBLIC_AGENT_OG_IMAGE=$NEXT_PUBLIC_AGENT_OG_IMAGE
ENV NEXT_PUBLIC_WELCOME_MESSAGE=$NEXT_PUBLIC_WELCOME_MESSAGE
ENV NEXT_PUBLIC_AGENT_TAGLINE=$NEXT_PUBLIC_AGENT_TAGLINE
ENV NEXT_PUBLIC_EXAMPLE_PROMPTS=$NEXT_PUBLIC_EXAMPLE_PROMPTS
ENV NEXT_PUBLIC_AGENT_KEYWORDS=$NEXT_PUBLIC_AGENT_KEYWORDS
ENV NEXT_PUBLIC_ABOUT_CONTENT=$NEXT_PUBLIC_ABOUT_CONTENT
ENV NEXT_PUBLIC_AGENT_X_USERNAME=$NEXT_PUBLIC_AGENT_X_USERNAME
ENV NEXT_PUBLIC_AGENT_DISCORD_SERVER=$NEXT_PUBLIC_AGENT_DISCORD_SERVER
ENV NEXT_PUBLIC_AGENT_WEBSITE_URL=$NEXT_PUBLIC_AGENT_WEBSITE_URL
ENV NEXT_PUBLIC_AGENT_GITHUB_URL=$NEXT_PUBLIC_AGENT_GITHUB_URL
ENV NEXT_PUBLIC_ENABLE_DEEP_RESEARCH=$NEXT_PUBLIC_ENABLE_DEEP_RESEARCH
ENV NEXT_PUBLIC_ENABLE_FILE_UPLOAD=$NEXT_PUBLIC_ENABLE_FILE_UPLOAD
ENV NEXT_PUBLIC_ENABLE_TEXT_TO_SPEECH=$NEXT_PUBLIC_ENABLE_TEXT_TO_SPEECH
ENV NEXT_PUBLIC_ENABLE_VOICE_INPUT=$NEXT_PUBLIC_ENABLE_VOICE_INPUT
ENV NEXT_PUBLIC_ENABLE_VOTING=$NEXT_PUBLIC_ENABLE_VOTING
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_WORLD_ID=$NEXT_PUBLIC_WORLD_ID

# Build the application
ENV NEXT_TELEMETRY_DISABLED=1
RUN bun run build

# Production image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create system user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy public files
COPY --from=builder /app/public ./public

# Copy built application
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the application
CMD ["bun", "server.js"]